name: Build Debug APKs

on:
  push:
    branches:
      - experimental
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package_variant: [ apt-android-7 ]

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Setup java 17 as required by gradle
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build debug APKs
        shell: bash
        env:
          TERMUX_PACKAGE_VARIANT: ${{ matrix.package_variant }}
        run: ./gradlew assembleDebug

      - name: Attach universal APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: termux-launcher-debug_${{ matrix.package_variant }}
          path: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/apk/debug/output-metadata.json
